export default interface User {
  id: number,
  customer_id: string,
  first_name: string,
  last_name: string,
  birth_date: string,
  rg: string,
  cpf: string,
  marital_status: string,
  nationality: string,
  profession: string,
  email: string,
  phone: string,
  street_address: string,
  address_number: string,
  neighbourhood: string,
  city: string,
  postal_code: string,
  state: string,
  role: 'admin' | 'user',
  super_admin: number,
  otp: string,
  otp_expiry: string,
  register_completed: number,
  status: 'PENDING' | 'ACTIVE' | 'SUSPENDED',
  created_at: Date,
  updated_at: Date
}